resolver 127.0.0.11 valid=30s;
client_max_body_size 1000M;

# Upstream for live app
upstream gme_app_upstream {
    zone gme_app_zone 64k;       # shared memory zone (required for resolver + upstream)
    server gme-app:8000 resolve; # resolve keyword forces DNS re-resolution
}

# Upstream for test app
upstream gme_test_upstream {
    zone gme_test_zone 64k;
    server gme-test:8000 resolve;
}

server {
    listen 80;
    server_name gme-live.opzo.app www.gme-live.opzo.app;

    location / {
        proxy_pass http://gme_app_upstream;

        proxy_http_version 1.1;
        proxy_set_header Connection "";

        proxy_set_header Host $host;
        proxy_set_header X-Real-IP $remote_addr;
        proxy_set_header X-Forwarded-For $proxy_add_x_forwarded_for;
        proxy_set_header X-Forwarded-Proto $scheme;
        proxy_set_header X-Forwarded-Ssl on;
    }
}

server {
    listen 80;
    server_name gme-test.opzo.app www.gme-test.opzo.app;

    location / {
        proxy_pass http://gme_test_upstream;

        proxy_http_version 1.1;
        proxy_set_header Connection "";

        proxy_set_header Host $host;
        proxy_set_header X-Real-IP $remote_addr;
        proxy_set_header X-Forwarded-For $proxy_add_x_forwarded_for;
        proxy_set_header X-Forwarded-Proto $scheme;
        proxy_set_header X-Forwarded-Ssl on;
    }
}
