<?php

namespace App\Http\Controllers;

use Illuminate\Http\Request;
use Barryvdh\DomPDF\Facade\Pdf;

class ReportController extends Controller
{
    //



    public function generatePdfReport(Request $request)
    {
        ini_set('max_execution_time', 300); // 5 minutes

        $title = $request->input('title', 'Monthly Sales Report');
        $subtitles = $request->input('subtitles', ['May 2025', 'Generated by Admin']);
        $table = $request->input('table');

        $table = base64_decode($table);

        // return view('pdf-templates.basic-template', compact('title', 'subtitles', 'table'));

        // Debug: Check the raw $table value
        // dd($table);

        // Attempt to clean up the $table data
        // Remove unwanted non-printable/control characters

        // Optionally, you can log or dd($table) here to inspect the cleaned result
        // dd($table);
        $pdf = Pdf::loadView('pdf-templates.basic-template', compact('title', 'subtitles', 'table'))
            ->setPaper('a4', 'portrait')
            ->setOptions([
                'margin-top' => 0,
                'margin-right' => 0,
                'margin-bottom' => 0,
                'margin-left' => 0,
            ]);

        return $pdf->stream('report.pdf');
    }

}
